# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: Curricula
    url: /#teaching
    weight: 20
  - name: Learning Technology
    url: /#tech
    weight: 21
  - name: Outcomes
    url: /#outcomes
    weight: 30
  - name: Expertise
    url: /#expertise
    weight: 40
  - name: Projects
    url: /project/
    weight: 50
